# Circuit Breaker pattern - Mari
resilience4j.circuitbreaker.instances.kafkaProducer.slidingWindowSize=5
resilience4j.circuitbreaker.instances.kafkaProducer.failureRateThreshold=50
resilience4j.circuitbreaker.instances.kafkaProducer.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.kafkaProducer.permittedNumberOfCallsInHalfOpenState=2